
package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InsulinDoseCalculator", targetNamespace = "http://server/", wsdlLocation = "http://localhost:8080/?wsdl")
public class InsulinDoseCalculator_Service
    extends Service
{

    private final static URL INSULINDOSECALCULATOR_WSDL_LOCATION;
    private final static WebServiceException INSULINDOSECALCULATOR_EXCEPTION;
    private final static QName INSULINDOSECALCULATOR_QNAME = new QName("http://server/", "InsulinDoseCalculator");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INSULINDOSECALCULATOR_WSDL_LOCATION = url;
        INSULINDOSECALCULATOR_EXCEPTION = e;
    }

    public InsulinDoseCalculator_Service() {
        super(__getWsdlLocation(), INSULINDOSECALCULATOR_QNAME);
    }

    public InsulinDoseCalculator_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), INSULINDOSECALCULATOR_QNAME, features);
    }

    public InsulinDoseCalculator_Service(URL wsdlLocation) {
        super(wsdlLocation, INSULINDOSECALCULATOR_QNAME);
    }

    public InsulinDoseCalculator_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INSULINDOSECALCULATOR_QNAME, features);
    }

    public InsulinDoseCalculator_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InsulinDoseCalculator_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InsulinDoseCalculator
     */
    @WebEndpoint(name = "InsulinDoseCalculatorPort")
    public InsulinDoseCalculator getInsulinDoseCalculatorPort() {
        return super.getPort(new QName("http://server/", "InsulinDoseCalculatorPort"), InsulinDoseCalculator.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InsulinDoseCalculator
     */
    @WebEndpoint(name = "InsulinDoseCalculatorPort")
    public InsulinDoseCalculator getInsulinDoseCalculatorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server/", "InsulinDoseCalculatorPort"), InsulinDoseCalculator.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INSULINDOSECALCULATOR_EXCEPTION!= null) {
            throw INSULINDOSECALCULATOR_EXCEPTION;
        }
        return INSULINDOSECALCULATOR_WSDL_LOCATION;
    }

}
